// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Data;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514095754_m4")]
    partial class m4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClanZahtev", b =>
                {
                    b.Property<int>("ZaduzeniClanId")
                        .HasColumnType("int");

                    b.Property<int>("ZahteviId")
                        .HasColumnType("int");

                    b.HasKey("ZaduzeniClanId", "ZahteviId");

                    b.HasIndex("ZahteviId");

                    b.ToTable("ClanZahtev");
                });

            modelBuilder.Entity("Notifikacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KoordinatorId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimalacId")
                        .HasColumnType("int");

                    b.Property<bool?>("Read")
                        .HasColumnType("bit");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KoordinatorId");

                    b.HasIndex("PrimalacId");

                    b.ToTable("Notifikacije");
                });

            modelBuilder.Entity("WebTemplate.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Agende");
                });

            modelBuilder.Entity("WebTemplate.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReciverId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("ReciverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("WebTemplate.Models.Deo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Tip")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremeDo")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("VremeOd")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.ToTable("Delovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Dogadjaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dogadjaji");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mejl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Korisnik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebTemplate.Models.Sesija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeoId")
                        .HasColumnType("int");

                    b.Property<string>("ImeSesije")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PredavacId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("VremeKraja")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("VremePocetka")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DeoId");

                    b.HasIndex("PredavacId");

                    b.ToTable("Sesije");
                });

            modelBuilder.Entity("WebTemplate.Models.VremeDostupnosti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("JeDostupan")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremeDo")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("VremeOd")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.ToTable("TabeleDostupnosti");
                });

            modelBuilder.Entity("WebTemplate.Models.Zahtev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<int?>("KoordinatorId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PosiljalacId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusZahteva")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogadjajId");

                    b.HasIndex("KoordinatorId");

                    b.HasIndex("PosiljalacId");

                    b.ToTable("Zahtevi");
                });

            modelBuilder.Entity("WebTemplate.Models.Clan", b =>
                {
                    b.HasBaseType("WebTemplate.Models.Korisnik");

                    b.Property<int?>("BrojIzvrsenihZahteva")
                        .HasColumnType("int");

                    b.Property<int?>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasIndex("DogadjajId");

                    b.ToTable("Korisnici", t =>
                        {
                            t.Property("DogadjajId")
                                .HasColumnName("Clan_DogadjajId");
                        });

                    b.HasDiscriminator().HasValue("Clan");
                });

            modelBuilder.Entity("WebTemplate.Models.Koordinator", b =>
                {
                    b.HasBaseType("WebTemplate.Models.Korisnik");

                    b.Property<int?>("AgendaId")
                        .HasColumnType("int");

                    b.Property<int?>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasIndex("AgendaId");

                    b.HasIndex("DogadjajId");

                    b.HasDiscriminator().HasValue("Koordinator");
                });

            modelBuilder.Entity("WebTemplate.Models.Participant", b =>
                {
                    b.HasBaseType("WebTemplate.Models.Korisnik");

                    b.Property<string>("Alerigije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<int?>("Ishrana")
                        .HasColumnType("int");

                    b.Property<string>("Komitet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremeDolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeOdlaska")
                        .HasColumnType("datetime2");

                    b.HasIndex("DogadjajId");

                    b.ToTable("Korisnici", t =>
                        {
                            t.Property("DogadjajId")
                                .HasColumnName("Participant_DogadjajId");
                        });

                    b.HasDiscriminator().HasValue("Participant");
                });

            modelBuilder.Entity("WebTemplate.Models.Predavac", b =>
                {
                    b.HasBaseType("WebTemplate.Models.Korisnik");

                    b.Property<string>("Alerigije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DogadjajId")
                        .HasColumnType("int");

                    b.Property<int?>("Ishrana")
                        .HasColumnType("int");

                    b.Property<string>("Komitet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremeDolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeOdlaska")
                        .HasColumnType("datetime2");

                    b.HasIndex("DogadjajId");

                    b.ToTable("Korisnici", t =>
                        {
                            t.Property("Alerigije")
                                .HasColumnName("Predavac_Alerigije");

                            t.Property("DogadjajId")
                                .HasColumnName("Predavac_DogadjajId");

                            t.Property("Ishrana")
                                .HasColumnName("Predavac_Ishrana");

                            t.Property("Komitet")
                                .HasColumnName("Predavac_Komitet");

                            t.Property("VremeDolaska")
                                .HasColumnName("Predavac_VremeDolaska");

                            t.Property("VremeOdlaska")
                                .HasColumnName("Predavac_VremeOdlaska");
                        });

                    b.HasDiscriminator().HasValue("Predavac");
                });

            modelBuilder.Entity("ClanZahtev", b =>
                {
                    b.HasOne("WebTemplate.Models.Clan", null)
                        .WithMany()
                        .HasForeignKey("ZaduzeniClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebTemplate.Models.Zahtev", null)
                        .WithMany()
                        .HasForeignKey("ZahteviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Notifikacija", b =>
                {
                    b.HasOne("WebTemplate.Models.Koordinator", null)
                        .WithMany("Notifikacije")
                        .HasForeignKey("KoordinatorId");

                    b.HasOne("WebTemplate.Models.Korisnik", "Primalac")
                        .WithMany()
                        .HasForeignKey("PrimalacId");

                    b.Navigation("Primalac");
                });

            modelBuilder.Entity("WebTemplate.Models.Agenda", b =>
                {
                    b.HasOne("WebTemplate.Models.Dogadjaj", "Dogadjaj")
                        .WithOne("Agenda")
                        .HasForeignKey("WebTemplate.Models.Agenda", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogadjaj");
                });

            modelBuilder.Entity("WebTemplate.Models.ChatMessage", b =>
                {
                    b.HasOne("WebTemplate.Models.Dogadjaj", "Dogadjaj")
                        .WithMany("Poruke")
                        .HasForeignKey("DogadjajId");

                    b.HasOne("WebTemplate.Models.Korisnik", "Reciver")
                        .WithMany("PrimljenePoruke")
                        .HasForeignKey("ReciverId");

                    b.HasOne("WebTemplate.Models.Korisnik", "Sender")
                        .WithMany("PoslatePoruke")
                        .HasForeignKey("SenderId");

                    b.Navigation("Dogadjaj");

                    b.Navigation("Reciver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("WebTemplate.Models.Deo", b =>
                {
                    b.HasOne("WebTemplate.Models.Agenda", "Agenda")
                        .WithMany("Delovi")
                        .HasForeignKey("AgendaId");

                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("WebTemplate.Models.Sesija", b =>
                {
                    b.HasOne("WebTemplate.Models.Deo", "Deo")
                        .WithMany("Sesije")
                        .HasForeignKey("DeoId");

                    b.HasOne("WebTemplate.Models.Predavac", "Predavac")
                        .WithMany("Sesije")
                        .HasForeignKey("PredavacId");

                    b.Navigation("Deo");

                    b.Navigation("Predavac");
                });

            modelBuilder.Entity("WebTemplate.Models.VremeDostupnosti", b =>
                {
                    b.HasOne("WebTemplate.Models.Clan", "Clan")
                        .WithMany("Tabela")
                        .HasForeignKey("ClanId");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("WebTemplate.Models.Zahtev", b =>
                {
                    b.HasOne("WebTemplate.Models.Dogadjaj", "Dogadjaj")
                        .WithMany("Zahtevi")
                        .HasForeignKey("DogadjajId");

                    b.HasOne("WebTemplate.Models.Koordinator", "Koordinator")
                        .WithMany()
                        .HasForeignKey("KoordinatorId");

                    b.HasOne("WebTemplate.Models.Korisnik", "Posiljalac")
                        .WithMany()
                        .HasForeignKey("PosiljalacId");

                    b.Navigation("Dogadjaj");

                    b.Navigation("Koordinator");

                    b.Navigation("Posiljalac");
                });

            modelBuilder.Entity("WebTemplate.Models.Clan", b =>
                {
                    b.HasOne("WebTemplate.Models.Dogadjaj", null)
                        .WithMany("Clanovi")
                        .HasForeignKey("DogadjajId");
                });

            modelBuilder.Entity("WebTemplate.Models.Koordinator", b =>
                {
                    b.HasOne("WebTemplate.Models.Agenda", null)
                        .WithMany("Koordinatori")
                        .HasForeignKey("AgendaId");

                    b.HasOne("WebTemplate.Models.Dogadjaj", "Dogadjaj")
                        .WithMany("Koordinatori")
                        .HasForeignKey("DogadjajId");

                    b.Navigation("Dogadjaj");
                });

            modelBuilder.Entity("WebTemplate.Models.Participant", b =>
                {
                    b.HasOne("WebTemplate.Models.Dogadjaj", null)
                        .WithMany("Participanti")
                        .HasForeignKey("DogadjajId");
                });

            modelBuilder.Entity("WebTemplate.Models.Predavac", b =>
                {
                    b.HasOne("WebTemplate.Models.Dogadjaj", null)
                        .WithMany("Predavaci")
                        .HasForeignKey("DogadjajId");
                });

            modelBuilder.Entity("WebTemplate.Models.Agenda", b =>
                {
                    b.Navigation("Delovi");

                    b.Navigation("Koordinatori");
                });

            modelBuilder.Entity("WebTemplate.Models.Deo", b =>
                {
                    b.Navigation("Sesije");
                });

            modelBuilder.Entity("WebTemplate.Models.Dogadjaj", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Clanovi");

                    b.Navigation("Koordinatori");

                    b.Navigation("Participanti");

                    b.Navigation("Poruke");

                    b.Navigation("Predavaci");

                    b.Navigation("Zahtevi");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Navigation("PoslatePoruke");

                    b.Navigation("PrimljenePoruke");
                });

            modelBuilder.Entity("WebTemplate.Models.Clan", b =>
                {
                    b.Navigation("Tabela");
                });

            modelBuilder.Entity("WebTemplate.Models.Koordinator", b =>
                {
                    b.Navigation("Notifikacije");
                });

            modelBuilder.Entity("WebTemplate.Models.Predavac", b =>
                {
                    b.Navigation("Sesije");
                });
#pragma warning restore 612, 618
        }
    }
}
